// GENERATED by scripts/gen-icons.mjs — do not edit by hand. Run `npm run icons`.
// Material Symbols (Rounded, 400). Each icon accepts `filled` for the active/selected state.
import { makeIcon as icon } from './icon-base'
import s_home from '@material-symbols/svg-400/rounded/home.svg?raw'
import s_homeFill from '@material-symbols/svg-400/rounded/home-fill.svg?raw'
import s_taskAlt from '@material-symbols/svg-400/rounded/task_alt.svg?raw'
import s_taskAltFill from '@material-symbols/svg-400/rounded/task_alt-fill.svg?raw'
import s_alarm from '@material-symbols/svg-400/rounded/alarm.svg?raw'
import s_alarmFill from '@material-symbols/svg-400/rounded/alarm-fill.svg?raw'
import s_localFireDepartment from '@material-symbols/svg-400/rounded/local_fire_department.svg?raw'
import s_localFireDepartmentFill from '@material-symbols/svg-400/rounded/local_fire_department-fill.svg?raw'
import s_block from '@material-symbols/svg-400/rounded/block.svg?raw'
import s_blockFill from '@material-symbols/svg-400/rounded/block-fill.svg?raw'
import s_fitnessCenter from '@material-symbols/svg-400/rounded/fitness_center.svg?raw'
import s_fitnessCenterFill from '@material-symbols/svg-400/rounded/fitness_center-fill.svg?raw'
import s_timer from '@material-symbols/svg-400/rounded/timer.svg?raw'
import s_timerFill from '@material-symbols/svg-400/rounded/timer-fill.svg?raw'
import s_barChart from '@material-symbols/svg-400/rounded/bar_chart.svg?raw'
import s_barChartFill from '@material-symbols/svg-400/rounded/bar_chart-fill.svg?raw'
import s_settings from '@material-symbols/svg-400/rounded/settings.svg?raw'
import s_settingsFill from '@material-symbols/svg-400/rounded/settings-fill.svg?raw'
import s_moreHoriz from '@material-symbols/svg-400/rounded/more_horiz.svg?raw'
import s_menu from '@material-symbols/svg-400/rounded/menu.svg?raw'
import s_apps from '@material-symbols/svg-400/rounded/apps.svg?raw'
import s_add from '@material-symbols/svg-400/rounded/add.svg?raw'
import s_close from '@material-symbols/svg-400/rounded/close.svg?raw'
import s_check from '@material-symbols/svg-400/rounded/check.svg?raw'
import s_edit from '@material-symbols/svg-400/rounded/edit.svg?raw'
import s_editFill from '@material-symbols/svg-400/rounded/edit-fill.svg?raw'
import s_delete from '@material-symbols/svg-400/rounded/delete.svg?raw'
import s_deleteFill from '@material-symbols/svg-400/rounded/delete-fill.svg?raw'
import s_search from '@material-symbols/svg-400/rounded/search.svg?raw'
import s_remove from '@material-symbols/svg-400/rounded/remove.svg?raw'
import s_undo from '@material-symbols/svg-400/rounded/undo.svg?raw'
import s_download from '@material-symbols/svg-400/rounded/download.svg?raw'
import s_upload from '@material-symbols/svg-400/rounded/upload.svg?raw'
import s_logout from '@material-symbols/svg-400/rounded/logout.svg?raw'
import s_login from '@material-symbols/svg-400/rounded/login.svg?raw'
import s_sync from '@material-symbols/svg-400/rounded/sync.svg?raw'
import s_openInNew from '@material-symbols/svg-400/rounded/open_in_new.svg?raw'
import s_share from '@material-symbols/svg-400/rounded/share.svg?raw'
import s_moreVert from '@material-symbols/svg-400/rounded/more_vert.svg?raw'
import s_arrowForward from '@material-symbols/svg-400/rounded/arrow_forward.svg?raw'
import s_arrowBack from '@material-symbols/svg-400/rounded/arrow_back.svg?raw'
import s_chevronLeft from '@material-symbols/svg-400/rounded/chevron_left.svg?raw'
import s_chevronRight from '@material-symbols/svg-400/rounded/chevron_right.svg?raw'
import s_keyboardArrowDown from '@material-symbols/svg-400/rounded/keyboard_arrow_down.svg?raw'
import s_keyboardArrowUp from '@material-symbols/svg-400/rounded/keyboard_arrow_up.svg?raw'
import s_arrowDropDown from '@material-symbols/svg-400/rounded/arrow_drop_down.svg?raw'
import s_dragIndicator from '@material-symbols/svg-400/rounded/drag_indicator.svg?raw'
import s_sort from '@material-symbols/svg-400/rounded/sort.svg?raw'
import s_filterList from '@material-symbols/svg-400/rounded/filter_list.svg?raw'
import s_fullscreen from '@material-symbols/svg-400/rounded/fullscreen.svg?raw'
import s_fullscreenExit from '@material-symbols/svg-400/rounded/fullscreen_exit.svg?raw'
import s_installDesktop from '@material-symbols/svg-400/rounded/install_desktop.svg?raw'
import s_keep from '@material-symbols/svg-400/rounded/keep.svg?raw'
import s_keepFill from '@material-symbols/svg-400/rounded/keep-fill.svg?raw'
import s_playArrow from '@material-symbols/svg-400/rounded/play_arrow.svg?raw'
import s_playArrowFill from '@material-symbols/svg-400/rounded/play_arrow-fill.svg?raw'
import s_pause from '@material-symbols/svg-400/rounded/pause.svg?raw'
import s_pauseFill from '@material-symbols/svg-400/rounded/pause-fill.svg?raw'
import s_stop from '@material-symbols/svg-400/rounded/stop.svg?raw'
import s_stopFill from '@material-symbols/svg-400/rounded/stop-fill.svg?raw'
import s_skipNext from '@material-symbols/svg-400/rounded/skip_next.svg?raw'
import s_skipNextFill from '@material-symbols/svg-400/rounded/skip_next-fill.svg?raw'
import s_restartAlt from '@material-symbols/svg-400/rounded/restart_alt.svg?raw'
import s_replay from '@material-symbols/svg-400/rounded/replay.svg?raw'
import s_snooze from '@material-symbols/svg-400/rounded/snooze.svg?raw'
import s_hourglassEmpty from '@material-symbols/svg-400/rounded/hourglass_empty.svg?raw'
import s_volumeUp from '@material-symbols/svg-400/rounded/volume_up.svg?raw'
import s_volumeUpFill from '@material-symbols/svg-400/rounded/volume_up-fill.svg?raw'
import s_noSound from '@material-symbols/svg-400/rounded/no_sound.svg?raw'
import s_mobileVibrate from '@material-symbols/svg-400/rounded/mobile_vibrate.svg?raw'
import s_notifications from '@material-symbols/svg-400/rounded/notifications.svg?raw'
import s_notificationsFill from '@material-symbols/svg-400/rounded/notifications-fill.svg?raw'
import s_notificationsOff from '@material-symbols/svg-400/rounded/notifications_off.svg?raw'
import s_notificationsActive from '@material-symbols/svg-400/rounded/notifications_active.svg?raw'
import s_notificationsActiveFill from '@material-symbols/svg-400/rounded/notifications_active-fill.svg?raw'
import s_alarmAdd from '@material-symbols/svg-400/rounded/alarm_add.svg?raw'
import s_alarmOn from '@material-symbols/svg-400/rounded/alarm_on.svg?raw'
import s_cloudDone from '@material-symbols/svg-400/rounded/cloud_done.svg?raw'
import s_cloudDoneFill from '@material-symbols/svg-400/rounded/cloud_done-fill.svg?raw'
import s_cloudOff from '@material-symbols/svg-400/rounded/cloud_off.svg?raw'
import s_cloudSync from '@material-symbols/svg-400/rounded/cloud_sync.svg?raw'
import s_syncProblem from '@material-symbols/svg-400/rounded/sync_problem.svg?raw'
import s_devices from '@material-symbols/svg-400/rounded/devices.svg?raw'
import s_progressActivity from '@material-symbols/svg-400/rounded/progress_activity.svg?raw'
import s_warning from '@material-symbols/svg-400/rounded/warning.svg?raw'
import s_warningFill from '@material-symbols/svg-400/rounded/warning-fill.svg?raw'
import s_info from '@material-symbols/svg-400/rounded/info.svg?raw'
import s_infoFill from '@material-symbols/svg-400/rounded/info-fill.svg?raw'
import s_help from '@material-symbols/svg-400/rounded/help.svg?raw'
import s_helpFill from '@material-symbols/svg-400/rounded/help-fill.svg?raw'
import s_checkCircle from '@material-symbols/svg-400/rounded/check_circle.svg?raw'
import s_checkCircleFill from '@material-symbols/svg-400/rounded/check_circle-fill.svg?raw'
import s_radioButtonUnchecked from '@material-symbols/svg-400/rounded/radio_button_unchecked.svg?raw'
import s_lock from '@material-symbols/svg-400/rounded/lock.svg?raw'
import s_lockFill from '@material-symbols/svg-400/rounded/lock-fill.svg?raw'
import s_visibility from '@material-symbols/svg-400/rounded/visibility.svg?raw'
import s_star from '@material-symbols/svg-400/rounded/star.svg?raw'
import s_starFill from '@material-symbols/svg-400/rounded/star-fill.svg?raw'
import s_flag from '@material-symbols/svg-400/rounded/flag.svg?raw'
import s_flagFill from '@material-symbols/svg-400/rounded/flag-fill.svg?raw'
import s_sell from '@material-symbols/svg-400/rounded/sell.svg?raw'
import s_sellFill from '@material-symbols/svg-400/rounded/sell-fill.svg?raw'
import s_label from '@material-symbols/svg-400/rounded/label.svg?raw'
import s_labelFill from '@material-symbols/svg-400/rounded/label-fill.svg?raw'
import s_repeat from '@material-symbols/svg-400/rounded/repeat.svg?raw'
import s_eventRepeat from '@material-symbols/svg-400/rounded/event_repeat.svg?raw'
import s_schedule from '@material-symbols/svg-400/rounded/schedule.svg?raw'
import s_scheduleFill from '@material-symbols/svg-400/rounded/schedule-fill.svg?raw'
import s_calendarMonth from '@material-symbols/svg-400/rounded/calendar_month.svg?raw'
import s_calendarMonthFill from '@material-symbols/svg-400/rounded/calendar_month-fill.svg?raw'
import s_calendarToday from '@material-symbols/svg-400/rounded/calendar_today.svg?raw'
import s_calendarTodayFill from '@material-symbols/svg-400/rounded/calendar_today-fill.svg?raw'
import s_calendarAddOn from '@material-symbols/svg-400/rounded/calendar_add_on.svg?raw'
import s_editCalendar from '@material-symbols/svg-400/rounded/edit_calendar.svg?raw'
import s_event from '@material-symbols/svg-400/rounded/event.svg?raw'
import s_eventFill from '@material-symbols/svg-400/rounded/event-fill.svg?raw'
import s_today from '@material-symbols/svg-400/rounded/today.svg?raw'
import s_todayFill from '@material-symbols/svg-400/rounded/today-fill.svg?raw'
import s_checklist from '@material-symbols/svg-400/rounded/checklist.svg?raw'
import s_list from '@material-symbols/svg-400/rounded/list.svg?raw'
import s_viewAgenda from '@material-symbols/svg-400/rounded/view_agenda.svg?raw'
import s_viewAgendaFill from '@material-symbols/svg-400/rounded/view_agenda-fill.svg?raw'
import s_gridView from '@material-symbols/svg-400/rounded/grid_view.svg?raw'
import s_gridViewFill from '@material-symbols/svg-400/rounded/grid_view-fill.svg?raw'
import s_spaceDashboard from '@material-symbols/svg-400/rounded/space_dashboard.svg?raw'
import s_spaceDashboardFill from '@material-symbols/svg-400/rounded/space_dashboard-fill.svg?raw'
import s_notes from '@material-symbols/svg-400/rounded/notes.svg?raw'
import s_inbox from '@material-symbols/svg-400/rounded/inbox.svg?raw'
import s_inboxFill from '@material-symbols/svg-400/rounded/inbox-fill.svg?raw'
import s_mail from '@material-symbols/svg-400/rounded/mail.svg?raw'
import s_mailFill from '@material-symbols/svg-400/rounded/mail-fill.svg?raw'
import s_link from '@material-symbols/svg-400/rounded/link.svg?raw'
import s_history from '@material-symbols/svg-400/rounded/history.svg?raw'
import s_addTask from '@material-symbols/svg-400/rounded/add_task.svg?raw'
import s_doneAll from '@material-symbols/svg-400/rounded/done_all.svg?raw'
import s_psychology from '@material-symbols/svg-400/rounded/psychology.svg?raw'
import s_psychologyFill from '@material-symbols/svg-400/rounded/psychology-fill.svg?raw'
import s_monitorHeart from '@material-symbols/svg-400/rounded/monitor_heart.svg?raw'
import s_monitorHeartFill from '@material-symbols/svg-400/rounded/monitor_heart-fill.svg?raw'
import s_bolt from '@material-symbols/svg-400/rounded/bolt.svg?raw'
import s_boltFill from '@material-symbols/svg-400/rounded/bolt-fill.svg?raw'
import s_workspacePremium from '@material-symbols/svg-400/rounded/workspace_premium.svg?raw'
import s_workspacePremiumFill from '@material-symbols/svg-400/rounded/workspace_premium-fill.svg?raw'
import s_trophy from '@material-symbols/svg-400/rounded/trophy.svg?raw'
import s_trophyFill from '@material-symbols/svg-400/rounded/trophy-fill.svg?raw'
import s_stars from '@material-symbols/svg-400/rounded/stars.svg?raw'
import s_starsFill from '@material-symbols/svg-400/rounded/stars-fill.svg?raw'
import s_stars2 from '@material-symbols/svg-400/rounded/stars_2.svg?raw'
import s_stars2Fill from '@material-symbols/svg-400/rounded/stars_2-fill.svg?raw'
import s_celebration from '@material-symbols/svg-400/rounded/celebration.svg?raw'
import s_celebrationFill from '@material-symbols/svg-400/rounded/celebration-fill.svg?raw'
import s_savings from '@material-symbols/svg-400/rounded/savings.svg?raw'
import s_savingsFill from '@material-symbols/svg-400/rounded/savings-fill.svg?raw'
import s_currencyRupee from '@material-symbols/svg-400/rounded/currency_rupee.svg?raw'
import s_mood from '@material-symbols/svg-400/rounded/mood.svg?raw'
import s_moodFill from '@material-symbols/svg-400/rounded/mood-fill.svg?raw'
import s_spa from '@material-symbols/svg-400/rounded/spa.svg?raw'
import s_spaFill from '@material-symbols/svg-400/rounded/spa-fill.svg?raw'
import s_selfImprovement from '@material-symbols/svg-400/rounded/self_improvement.svg?raw'
import s_directionsRun from '@material-symbols/svg-400/rounded/directions_run.svg?raw'
import s_waterDrop from '@material-symbols/svg-400/rounded/water_drop.svg?raw'
import s_waterDropFill from '@material-symbols/svg-400/rounded/water_drop-fill.svg?raw'
import s_menuBook from '@material-symbols/svg-400/rounded/menu_book.svg?raw'
import s_menuBookFill from '@material-symbols/svg-400/rounded/menu_book-fill.svg?raw'
import s_bedtime from '@material-symbols/svg-400/rounded/bedtime.svg?raw'
import s_bedtimeFill from '@material-symbols/svg-400/rounded/bedtime-fill.svg?raw'
import s_smokingRooms from '@material-symbols/svg-400/rounded/smoking_rooms.svg?raw'
import s_smokingRoomsFill from '@material-symbols/svg-400/rounded/smoking_rooms-fill.svg?raw'
import s_smokeFree from '@material-symbols/svg-400/rounded/smoke_free.svg?raw'
import s_noFood from '@material-symbols/svg-400/rounded/no_food.svg?raw'
import s_noFoodFill from '@material-symbols/svg-400/rounded/no_food-fill.svg?raw'
import s_target from '@material-symbols/svg-400/rounded/target.svg?raw'
import s_routine from '@material-symbols/svg-400/rounded/routine.svg?raw'
import s_routineFill from '@material-symbols/svg-400/rounded/routine-fill.svg?raw'
import s_monitorWeight from '@material-symbols/svg-400/rounded/monitor_weight.svg?raw'
import s_monitorWeightFill from '@material-symbols/svg-400/rounded/monitor_weight-fill.svg?raw'
import s_trendingUp from '@material-symbols/svg-400/rounded/trending_up.svg?raw'
import s_showChart from '@material-symbols/svg-400/rounded/show_chart.svg?raw'
import s_leaderboard from '@material-symbols/svg-400/rounded/leaderboard.svg?raw'
import s_leaderboardFill from '@material-symbols/svg-400/rounded/leaderboard-fill.svg?raw'
import s_analytics from '@material-symbols/svg-400/rounded/analytics.svg?raw'
import s_analyticsFill from '@material-symbols/svg-400/rounded/analytics-fill.svg?raw'
import s_insertChart from '@material-symbols/svg-400/rounded/insert_chart.svg?raw'
import s_insertChartFill from '@material-symbols/svg-400/rounded/insert_chart-fill.svg?raw'
import s_palette from '@material-symbols/svg-400/rounded/palette.svg?raw'
import s_paletteFill from '@material-symbols/svg-400/rounded/palette-fill.svg?raw'
import s_darkMode from '@material-symbols/svg-400/rounded/dark_mode.svg?raw'
import s_darkModeFill from '@material-symbols/svg-400/rounded/dark_mode-fill.svg?raw'
import s_lightMode from '@material-symbols/svg-400/rounded/light_mode.svg?raw'
import s_lightModeFill from '@material-symbols/svg-400/rounded/light_mode-fill.svg?raw'
import s_contrast from '@material-symbols/svg-400/rounded/contrast.svg?raw'
import s_accountCircle from '@material-symbols/svg-400/rounded/account_circle.svg?raw'
import s_accountCircleFill from '@material-symbols/svg-400/rounded/account_circle-fill.svg?raw'
import s_backup from '@material-symbols/svg-400/rounded/backup.svg?raw'
import s_backupFill from '@material-symbols/svg-400/rounded/backup-fill.svg?raw'
import s_deleteForever from '@material-symbols/svg-400/rounded/delete_forever.svg?raw'
import s_deleteForeverFill from '@material-symbols/svg-400/rounded/delete_forever-fill.svg?raw'
import s_language from '@material-symbols/svg-400/rounded/language.svg?raw'
import s_tune from '@material-symbols/svg-400/rounded/tune.svg?raw'

export type { IconComponent, IconProps } from './icon-base'

export const Home = icon('Home', s_home, s_homeFill)
export const CheckSquare = icon('CheckSquare', s_taskAlt, s_taskAltFill)
export const AlarmClock = icon('AlarmClock', s_alarm, s_alarmFill)
export const Flame = icon('Flame', s_localFireDepartment, s_localFireDepartmentFill)
export const ShieldOff = icon('ShieldOff', s_block, s_blockFill)
export const Dumbbell = icon('Dumbbell', s_fitnessCenter, s_fitnessCenterFill)
export const Timer = icon('Timer', s_timer, s_timerFill)
export const BarChart3 = icon('BarChart3', s_barChart, s_barChartFill)
export const Settings = icon('Settings', s_settings, s_settingsFill)
export const MoreHorizontal = icon('MoreHorizontal', s_moreHoriz)
export const Menu = icon('Menu', s_menu)
export const Apps = icon('Apps', s_apps)
export const Plus = icon('Plus', s_add)
export const X = icon('X', s_close)
export const Check = icon('Check', s_check)
export const Pencil = icon('Pencil', s_edit, s_editFill)
export const Trash2 = icon('Trash2', s_delete, s_deleteFill)
export const Search = icon('Search', s_search)
export const Minus = icon('Minus', s_remove)
export const Undo = icon('Undo', s_undo)
export const Download = icon('Download', s_download)
export const Upload = icon('Upload', s_upload)
export const LogOut = icon('LogOut', s_logout)
export const Login = icon('Login', s_login)
export const RefreshCw = icon('RefreshCw', s_sync)
export const OpenInNew = icon('OpenInNew', s_openInNew)
export const Share = icon('Share', s_share)
export const MoreVert = icon('MoreVert', s_moreVert)
export const ArrowRight = icon('ArrowRight', s_arrowForward)
export const ArrowLeft = icon('ArrowLeft', s_arrowBack)
export const ChevronLeft = icon('ChevronLeft', s_chevronLeft)
export const ChevronRight = icon('ChevronRight', s_chevronRight)
export const ChevronDown = icon('ChevronDown', s_keyboardArrowDown)
export const ChevronUp = icon('ChevronUp', s_keyboardArrowUp)
export const ArrowDropDown = icon('ArrowDropDown', s_arrowDropDown)
export const GripVertical = icon('GripVertical', s_dragIndicator)
export const Sort = icon('Sort', s_sort)
export const FilterList = icon('FilterList', s_filterList)
export const Maximize2 = icon('Maximize2', s_fullscreen)
export const Minimize2 = icon('Minimize2', s_fullscreenExit)
export const Smartphone = icon('Smartphone', s_installDesktop)
export const Pin = icon('Pin', s_keep, s_keepFill)
export const Play = icon('Play', s_playArrow, s_playArrowFill)
export const Pause = icon('Pause', s_pause, s_pauseFill)
export const Square = icon('Square', s_stop, s_stopFill)
export const SkipForward = icon('SkipForward', s_skipNext, s_skipNextFill)
export const RotateCcw = icon('RotateCcw', s_restartAlt)
export const Replay = icon('Replay', s_replay)
export const Snooze = icon('Snooze', s_snooze)
export const Hourglass = icon('Hourglass', s_hourglassEmpty)
export const Volume2 = icon('Volume2', s_volumeUp, s_volumeUpFill)
export const VolumeOff = icon('VolumeOff', s_noSound)
export const Vibrate = icon('Vibrate', s_mobileVibrate)
export const Bell = icon('Bell', s_notifications, s_notificationsFill)
export const BellOff = icon('BellOff', s_notificationsOff)
export const BellRing = icon('BellRing', s_notificationsActive, s_notificationsActiveFill)
export const AlarmAdd = icon('AlarmAdd', s_alarmAdd)
export const AlarmOn = icon('AlarmOn', s_alarmOn)
export const Cloud = icon('Cloud', s_cloudDone, s_cloudDoneFill)
export const CloudOff = icon('CloudOff', s_cloudOff)
export const CloudSync = icon('CloudSync', s_cloudSync)
export const SyncProblem = icon('SyncProblem', s_syncProblem)
export const HardDrive = icon('HardDrive', s_devices)
export const Loader2 = icon('Loader2', s_progressActivity)
export const TriangleAlert = icon('TriangleAlert', s_warning, s_warningFill)
export const Info = icon('Info', s_info, s_infoFill)
export const Help = icon('Help', s_help, s_helpFill)
export const CheckCircle = icon('CheckCircle', s_checkCircle, s_checkCircleFill)
export const Circle = icon('Circle', s_radioButtonUnchecked)
export const Lock = icon('Lock', s_lock, s_lockFill)
export const Visibility = icon('Visibility', s_visibility)
export const Star = icon('Star', s_star, s_starFill)
export const Flag = icon('Flag', s_flag, s_flagFill)
export const Tag = icon('Tag', s_sell, s_sellFill)
export const Label = icon('Label', s_label, s_labelFill)
export const Repeat = icon('Repeat', s_repeat)
export const EventRepeat = icon('EventRepeat', s_eventRepeat)
export const Clock = icon('Clock', s_schedule, s_scheduleFill)
export const CalendarDays = icon('CalendarDays', s_calendarMonth, s_calendarMonthFill)
export const CalendarToday = icon('CalendarToday', s_calendarToday, s_calendarTodayFill)
export const CalendarPlus = icon('CalendarPlus', s_calendarAddOn)
export const EditCalendar = icon('EditCalendar', s_editCalendar)
export const Event = icon('Event', s_event, s_eventFill)
export const Today = icon('Today', s_today, s_todayFill)
export const ListChecks = icon('ListChecks', s_checklist)
export const List = icon('List', s_list)
export const ViewAgenda = icon('ViewAgenda', s_viewAgenda, s_viewAgendaFill)
export const Grid2x2 = icon('Grid2x2', s_gridView, s_gridViewFill)
export const Dashboard = icon('Dashboard', s_spaceDashboard, s_spaceDashboardFill)
export const Notes = icon('Notes', s_notes)
export const Inbox = icon('Inbox', s_inbox, s_inboxFill)
export const Mail = icon('Mail', s_mail, s_mailFill)
export const Link2 = icon('Link2', s_link)
export const History = icon('History', s_history)
export const AddTask = icon('AddTask', s_addTask)
export const DoneAll = icon('DoneAll', s_doneAll)
export const Brain = icon('Brain', s_psychology, s_psychologyFill)
export const HeartPulse = icon('HeartPulse', s_monitorHeart, s_monitorHeartFill)
export const Zap = icon('Zap', s_bolt, s_boltFill)
export const Award = icon('Award', s_workspacePremium, s_workspacePremiumFill)
export const Trophy = icon('Trophy', s_trophy, s_trophyFill)
export const Stars = icon('Stars', s_stars, s_starsFill)
export const Sparkles = icon('Sparkles', s_stars2, s_stars2Fill)
export const Celebration = icon('Celebration', s_celebration, s_celebrationFill)
export const Savings = icon('Savings', s_savings, s_savingsFill)
export const IndianRupee = icon('IndianRupee', s_currencyRupee)
export const Mood = icon('Mood', s_mood, s_moodFill)
export const Spa = icon('Spa', s_spa, s_spaFill)
export const SelfImprovement = icon('SelfImprovement', s_selfImprovement)
export const Run = icon('Run', s_directionsRun)
export const Water = icon('Water', s_waterDrop, s_waterDropFill)
export const Book = icon('Book', s_menuBook, s_menuBookFill)
export const Bedtime = icon('Bedtime', s_bedtime, s_bedtimeFill)
export const Moon = icon('Moon', s_bedtime, s_bedtimeFill)
export const Smoking = icon('Smoking', s_smokingRooms, s_smokingRoomsFill)
export const SmokeFree = icon('SmokeFree', s_smokeFree)
export const NoFood = icon('NoFood', s_noFood, s_noFoodFill)
export const Target = icon('Target', s_target)
export const Routine = icon('Routine', s_routine, s_routineFill)
export const MonitorWeight = icon('MonitorWeight', s_monitorWeight, s_monitorWeightFill)
export const TrendingUp = icon('TrendingUp', s_trendingUp)
export const ShowChart = icon('ShowChart', s_showChart)
export const Leaderboard = icon('Leaderboard', s_leaderboard, s_leaderboardFill)
export const Analytics = icon('Analytics', s_analytics, s_analyticsFill)
export const InsertChart = icon('InsertChart', s_insertChart, s_insertChartFill)
export const Palette = icon('Palette', s_palette, s_paletteFill)
export const DarkMode = icon('DarkMode', s_darkMode, s_darkModeFill)
export const LightMode = icon('LightMode', s_lightMode, s_lightModeFill)
export const Contrast = icon('Contrast', s_contrast)
export const AccountCircle = icon('AccountCircle', s_accountCircle, s_accountCircleFill)
export const Backup = icon('Backup', s_backup, s_backupFill)
export const DeleteForever = icon('DeleteForever', s_deleteForever, s_deleteForeverFill)
export const Language = icon('Language', s_language)
export const Tune = icon('Tune', s_tune)
